version: 2
updates:

  # Github Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly

  # web
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly

  # random-knowledge subrepo
  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: monthly
